language: node_js
dist: trusty
node_js:
  - node
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - '.npm'
install:
  - yarn install --frozen-lockfile
  - yarn global add codecov
script:
  - yarn build
  - yarn lint
  - yarn size
  - yarn test --coverage
  - codecov
notifications:
  slack:
    rooms:
      - secure: MgFWIfJr0mQMtwJ/fMVqeo/eO2dDRUYfCH+93JlVuUhiq85cEupa90FuHMRXRd0ZLPHBf/EscCLPPtrCe+o7XlUeevbdQX5hSF6UNp1QQVbgEM/Kl/6Di05vyAo0Dg2fVnpJn7yhk4sKgpJPjHV4iEyzZLo8aZiT/57ra1rwPpR+g6VNBsOhjC+BwCVNrSv0zUbx4eIb2cdHGufkM2uMEp/i6y9a378MJyfe31l2mhaf0/gPXtye+vmaKgSlJGm/YdTu9BGNdCAbb/oODTkAsWeHD+febDG6NtqeHEt/J7aTlWHIgJ99IPQAFd4m9KMqjpb2xC3Y5CDy2ceFBl9N1i0TWwu6L+vBy7iSKFrJFxYO3Z4mOPlxVv9i2fY/dDidMHu5GcrrMQH9sptyn8fFScfVsFXz4hEFUS6NHFOxYLsEkQf+ACkpIsVXStYBnTckioMMNsbVlSA+RTCmuahEOgVfiJbJPIhgcvdslPTW3iZwGBGVX+K6qdIqKhiXzzjKAApxVMcX3xJDPgTzzw/41ljxZAntTTG4CKDPI3HOu3fbhOiAKydGz5dfk+gabYyBngJwEAHfYSEKrJJ7s8riwL9pF2Hab++PAcpCyBIYrNcKxE8NKn17X/gyPO+WXy/rJu0VkzsyYmOuRL4NMPmkHNqMJYno1cVTMlVNuPINHYU=
